function SWAPICounts2024 = importCtFiles(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  SWAPICOUNTS2024 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SWAPICOUNTS2024 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  SWAPICounts2024 = importfile1("/Users/lykhoo/Library/CloudStorage/OneDrive-PrincetonUniversity/Documents/Lab/SWAPI Cal/FM-Cal/Data_analysis/2024.03.27/passband_16keVHe/SWAPI-Counts_2024.03.27_34.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Mar-2024 18:33:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["StartTime", "PCEMV", "SCEMV", "ESAV", "PRMRate", "SECRate", "COINRate", "PCEMI", "SCEMI", "ESAI"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "StartTime", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "StartTime", "EmptyFieldRule", "auto");

% Import the data
SWAPICounts2024 = readtable(filename, opts);

end