function motionFile = import_motionfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  MOTIONSYSTEMCONTROLV1 = IMPORTFILE1(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  MOTIONSYSTEMCONTROLV1 = IMPORTFILE1(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MotionSystemControlv1 = importfile1("/Users/lykhoo/Library/CloudStorage/OneDrive-PrincetonUniversity/Documents/Lab/SWAPI Cal/FM-Cal/Data_analysis/Motion-System-Control_v1.4_2024.03.28_3.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Apr-2024 22:14:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["UserName", "TSMA", "TestDescription", "SWAPIFMTesting", "VarName5", "VarName6", "Var7"];
opts.SelectedVariableNames = ["UserName", "TSMA", "TestDescription", "SWAPIFMTesting", "VarName5", "VarName6"];
opts.VariableTypes = ["string", "categorical", "double", "categorical", "double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["UserName", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["UserName", "TSMA", "SWAPIFMTesting", "VarName6", "Var7"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TestDescription", "TrimNonNumeric", true);
opts = setvaropts(opts, "TestDescription", "ThousandsSeparator", ",");

% Import the data
motionFile = readtable(filename, opts);

end