function HVRAMP = importHVPSfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HVRAMPPCEM2024 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  HVRAMPPCEM2024 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  HVRAMPPCEM2024 = importfile("/Users/lykhoo/Library/CloudStorage/OneDrive-PrincetonUniversity/Documents/Lab/SWAPI Cal/FM-Cal/Data_analysis/2024.03.27/gain_curves/HVRAMP_PCEM_2024.03.27_8.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Mar-2024 17:10:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "SupplyName", "CommandSent", "Action", "Voltage", "Current", "HVStatus", "Errors", "PRMRate", "SECRate", "COINRate"];
opts.VariableTypes = ["string", "categorical", "double", "categorical", "double", "double", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TimeStamp", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["TimeStamp", "SupplyName", "Action", "HVStatus"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["CommandSent", "Errors"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["CommandSent", "Errors"], "ThousandsSeparator", ",");

% Import the data
HVRAMP = readtable(filename, opts);

end